INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (1, 1, 'First team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (2, 1, 'Second team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (3, 1, 'Third team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (4, 1, 'Fourth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (5, 1, 'Fifth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (6, 1, 'Sixth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (7, 1, 'Seventh team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (8, 1, 'Eight team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (9, 1, 'Ninth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (10, 1, 'Tenth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (11, 3, 'Eleventh team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (12, 20, 'Twelfth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (13, 20, 'Thirteenth team');
INSERT INTO rowMatch.teams (id,  member_count, name) VALUES (14, 2, 'Fourteenth team');
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (1, 1700, 4, 1);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (2, 3500, 6, 2);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (3, 2800, 3, 3);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (4, 3500, 10, 4);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (5, 1400, 9, 5);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (6, 2300, 3, 6);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (7, 3800, 10, 7);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (8, 2900, 1, 8);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (9, 3000, 8, 9);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (10, 1300, 2, 10);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (11, 2900, 4, 11);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (12, 3500, 7, 12);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (13, 500, 3, 13);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (14, 3400, 1, 14);
INSERT INTO rowMatch.users (id, coin_balance, level, team_id) VALUES (15, 3900, 10, null);
